document.write("<div style='position:relative;'>");
document.write("&nbsp;<font color='#FF6600'><a href='http://www.lib.ru.ac.th/about/index.html' target='_self'>About</a> | ");
document.write("<a href='http://www.lib.ru.ac.th/service/index.html' target='_self' title=' Database Services '>Services</a> | ");
document.write("<a href='http://www.lib.ru.ac.th/contents.html' target='_self'>e-Contents</a> | ");
document.write("<a href='http://www.lib.ru.ac.th/document/index.html' target='_self'>e-Docs</a> | ");
document.write("<a href='http://www.lib.ru.ac.th/knowledge/index.html' target='_self'>Knowledge</a> | ");
document.write("<a href='http://www.lib.ru.ac.th/links.html' target='_self'>Links</a> | ");
document.write("<a href='http://www.lib.ru.ac.th/download.html' target='_self'>Download</a> | ");
document.write("<a href='http://www.lib.ru.ac.th/forum/'>Forum</a> | ");
document.write("<a href='http://www.lib.ru.ac.th/faq/index.html' target='_self'>FAQ</a> | ");
document.write("<a href='http://www.lib.ru.ac.th/sitemap.html' target='_self' title='á¼¹¼Ñ§àÇçºä«µì'>Site map</a> |</font> ");
document.write("<div style='position:absolute;right:0px;bottom:0px;'>");
document.write("<a href='http://www.lib.ru.ac.th/english/' target='_self' title=' English Version '><img src='http://www.lib.ru.ac.th/images/icn_eng_web.gif' align='absbottom' border='0'></a>");
document.write("</div></div>");